apiVersion: v2      #The chart API version (required)
name: nginx         #The name of the chart (required)
version: 1.0.0      #The version of the chart (required)
description: This is nginx deployment       #A single-sentence description of this project (optional)
appversion: 1.2.0